version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432"
    environment:
      POSTGRES_USER: yashbalyan
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: rbac
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
